name: Terraform PR checks

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]

jobs:
  terraform-plan:
    name: Terraform plan on PR
    uses: ./.github/workflows/terraform-run.yml
    with:
      command: plan
